// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetrpkuWeb.Server.Data;

namespace PetrpkuWeb.Server.Migrations
{
    [DbContext(typeof(DbStorageContext))]
    [Migration("20190813114038_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview7.19362.6");

            modelBuilder.Entity("PetrpkuWeb.Shared.Models.Article", b =>
                {
                    b.Property<int>("ArticleId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<DateTime>("PublishDate");

                    b.Property<string>("Title");

                    b.Property<int>("UserInfoId");

                    b.HasKey("ArticleId");

                    b.HasIndex("UserInfoId");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("PetrpkuWeb.Shared.Models.Duty", b =>
                {
                    b.Property<int>("DutyId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DayOfDuty");

                    b.Property<int>("UserInfoId");

                    b.HasKey("DutyId");

                    b.HasIndex("UserInfoId");

                    b.ToTable("Duties");
                });

            modelBuilder.Entity("PetrpkuWeb.Shared.Models.UserInfo", b =>
                {
                    b.Property<int>("UserInfoId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Birthday");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("LoginName");

                    b.Property<string>("MidleName");

                    b.Property<string>("Office");

                    b.Property<string>("Phone");

                    b.Property<string>("PhotoUrl");

                    b.Property<string>("WorkingPosition");

                    b.HasKey("UserInfoId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PetrpkuWeb.Shared.Models.Article", b =>
                {
                    b.HasOne("PetrpkuWeb.Shared.Models.UserInfo", "Author")
                        .WithMany("Articles")
                        .HasForeignKey("UserInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PetrpkuWeb.Shared.Models.Duty", b =>
                {
                    b.HasOne("PetrpkuWeb.Shared.Models.UserInfo", "AssignedTo")
                        .WithMany("DaysOfDuty")
                        .HasForeignKey("UserInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
